interface AwsEvent {
	body: string;
	headers: {
	  Host: string;
	  Connection: string;
	  ContentLength: string;
	  Authorization: string;
	  CacheControl: string;
	  ContentType: string;
	  UserAgent: string;
	  PostmanToken: string;
	  Accept: string;
	  Origin: string;
	  SecFetchSite: string;
	  SecFetchMode: string;
	  SecFetchDest: string;
	  AcceptEncoding: string;
	  AcceptLanguage: string;
	},
	httpMethod: string;
	isBase64Encoded: boolean;
	multiValueHeaders: {
	  Host: any,
	  Connection: any,
	  ContentLength: any,
	  Authorization: any,
	  CacheControl: any;
	  ContentType: any;
	  UserAgent: any;
	  PostmanToken: any;
	  Accept: any;
	  Origin: any;
	  SecFetchSite: any;
	  SecFetchMode: any;
	  SecFetchDest: any;
	  AcceptEncoding: any;
	  AcceptLanguage: any;
	},
	multiValueQueryStringParameters: any,
	path: string;
	pathParameters: any,
	queryStringParameters: any,
	requestContext: {
		accountId: string;
		apiId: string;
		authorizer: {
		  claims: any;
		  scopes: any;
		  principalId: string;
		},
		domainName: string;
		domainPrefix: string;
		extendedRequestId: string;
		httpMethod: string;
		identity: {
		  accessKey: any,
		  accountId: string;
		  apiKey: string;
		  caller: string;
		  cognitoAuthenticationProvider: string;
		  cognitoAuthenticationType: string;
		  cognitoIdentityId: string;
		  cognitoIdentityPoolId: string;
		  principalOrgId: string;
		  sourceIp: string;
		  user: string;
		  userAgent: string;
		  userArn: string;
		},
		path: string;
		protocol: string;
		requestId: string;
		requestTime: string;
		requestTimeEpoch: number,
		resourceId: string;
		resourcePath: string;
		stage: string;
	}
	resource: string;
	stageVariables: any;
}